# Docs for the Azure Web Apps Deploy action: https://github.com/azure/functions-action
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and Deploy Azure Function

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: 'app/'
  NODE_VERSION: '18.x'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v2

      - name: Setup Node ${{ env.NODE_VERSION }} Environment
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}
      
      - name: 'Copy files'
        shell: bash
        run: |
          pwd
          mkdir -p ./repo
          cp -r ./${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }} ./repo/

      - name: 'Resolve Project Dependencies Using Npm'
        shell: bash
        run: |
          pushd './repo/${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
          npm install
          npm list
          npm run build --if-present
          npm run test --if-present
          popd

      - name: 'Run Azure Functions Action'
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: 'filefusion-function'
          slot-name: 'Production'
          package: './repo/${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_51437C3B67334161ACA9314BF7C564CC }}
